all:
	cd serialRMI; make
	cd genBot; make

#	Takes too long to start even if nothing need to be recompiled
#	Will be done automatically if needed anyway
#	cd genBotWI; make

clean:
	cd serialRMI; make clean
	cd genBot; make clean

#	In the hope that the play framework gets its build system right
#	and a play rebuild takes a long time, don't clean it out here.
